/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appcambio;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @developer Fabiano
 */
public class TelaCambio extends javax.swing.JFrame {

    /**
     * Creates new form TelaCambio
     */
    public TelaCambio() {
        initComponents();
        jText_Valor.setText("0.00");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCB_Moeda = new javax.swing.JComboBox<>();
        jText_Resultado = new javax.swing.JTextField();
        jText_Valor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("App Cambio");
        setResizable(false);

        jLabel1.setText("Desenvolvido por Fabiano Dolzanes");

        jCB_Moeda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCB_Moeda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD - Dolar", "EUR - Euro", "JPY - Iene", " " }));
        jCB_Moeda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_MoedaActionPerformed(evt);
            }
        });

        jText_Resultado.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jText_Resultado.setEnabled(false);

        jText_Valor.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Real (R$)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jText_Resultado)
                        .addComponent(jCB_Moeda, 0, 208, Short.MAX_VALUE)
                        .addComponent(jText_Valor))
                    .addComponent(jLabel2))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jText_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCB_Moeda, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jText_Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCB_MoedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_MoedaActionPerformed
        double totalResult = 0.00;
        Cambio cambio = new Cambio();
        
        String valorDigitado = jText_Valor.getText(); 
        double valor = Double.parseDouble(valorDigitado);
                
        int op = jCB_Moeda.getSelectedIndex(); 
        
        switch (op) {
            case 0 : 
                totalResult = cambio.Dolar(valor);
                break; 
            case 1 : 
                totalResult = cambio.Euro(valor);
                break;
            case 2 : 
                totalResult = cambio.Iene(valor);
                break;
            default:
                jText_Valor.setText("");
                jText_Resultado.setText("");
                JOptionPane.showMessageDialog(rootPane, "ERROR - Opção Invalido");
        }
                         
        DecimalFormat df = new DecimalFormat("0.000");
        jText_Resultado.setText(df.format(totalResult));
        
    }//GEN-LAST:event_jCB_MoedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCambio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCB_Moeda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jText_Resultado;
    private javax.swing.JTextField jText_Valor;
    // End of variables declaration//GEN-END:variables
}
